### ISSUE TITLE
websocket support in the upcoming release

### ISSUE THREAD

**Issue by ziirish** [CoffeeITWorks/ansible_burpui_server#3]
Hello Pablo,

I just wanted to let you know the next version of burp-ui will come with optional support for websockets.
The according docs are [here](http://burp-ui.readthedocs.io/en/latest/advanced_usage.html#websocket) and [there](http://burp-ui.readthedocs.io/en/latest/websocket.html)

**Comment by pablodav** [comment]
Great! thanks for notifying me, I'm will take care of these options to be added to this role too. 

But could you help me understand more about it? 

What I see now about it: 

Since v0.6.0, Burp-UI supports WebSockets for better/smarter notifications. In order to use this feature, you need some extra requirements:

What better/smarter notifications means? Does it help in burp-ui internals? or in the burp-ui webpage? 

Looks very recommended to be enabled by default right?

**Comment by ziirish** [comment]
Hi Pablo,

When I release v0.6.0, I don't think websockets will bring a lot of exciting features.
Right now it only allows the *blinking* "backup running" notification to be smarter (ie. the client does not have to refresh the page every X seconds. If websockets are not enabled it will fallback to a javascript auto-refresh like before).

In the future, websockets will allow a real notification system. For instance, you will be able to launch a restoration, then leave the page to check whatever you want and then when the archive is ready you'll have a popup or something telling you your download is available.

Another feature I'm thinking about is to force the refresh of the interface of all the connected users whenever you add a new client.

But right now websockets don't do much things ;-)
